import type { ModMail } from "@devvit/protos";
import type { TriggerContext } from "@devvit/public-api";
import {
  attachReplyByConversation,
  readVerify,
  writeVerify,
} from "../lib/verifyAuthor.js";
import { markHandled, addToDailySpend, getDailySpend } from "../redis.js";
import { classifyReply } from "../ensemble/replyClassifier.js";
import { AppSetting } from "../settings.js";

/**
 * Catches replies from authors to our verify-author DM and attaches the
 * reply text to the score's review card.
 *
 * Filters:
 *   - Must be from `participant_user` (the author, not a mod or internal)
 *   - Must not be auto-generated (no loops)
 *   - Must match a conversationId we previously sent (verifyAuthor's
 *     reverse index `sg:verify-conv:<convId>`)
 *
 * The trigger fires for *every* modmail event in the sub, so the cheap
 * conversationId lookup in Redis is what gates us to only our own threads.
 */
export async function onModMail(
  event: ModMail,
  context: TriggerContext,
): Promise<void> {
  if (!event.conversationId || !event.messageId) return;
  if (event.isAutoGenerated) return;

  // Only the post/comment author's reply matters — skip mod-side messages
  // and internal mod-discussion messages.
  if (event.messageAuthorType !== "participant_user") return;

  // Dedupe — same messageId can re-fire.
  const dedup = await markHandled(
    context,
    "modMail",
    event.messageId,
  );
  if (!dedup) return;

  // Fetch the conversation and pick the EXACT message for this event. We
  // deliberately do NOT fall back to "latest user message" — earlier code
  // did, which re-classified the wrong message when an author sent
  // several short replies in sequence (each event fires; the fallback
  // always picks the latest body regardless of which event it was).
  let body = "";
  try {
    const res = await context.reddit.modMail.getConversation({
      conversationId: event.conversationId,
      markRead: false,
    });
    const messages = res.conversation?.messages ?? {};
    const exact = messages[event.messageId];
    if (!exact) {
      console.warn(
        `Slopguard onModMail: message ${event.messageId} not in conversation ${event.conversationId} — skipping`,
      );
      return;
    }
    body = exact.bodyMarkdown ?? exact.body ?? "";
  } catch (err) {
    console.warn(
      `Slopguard onModMail: failed to fetch conversation ${event.conversationId}: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
    return;
  }

  if (!body.trim()) return;

  const record = await attachReplyByConversation(context, {
    conversationId: event.conversationId,
    replyText: body,
  });

  if (!record) return;
  console.log(
    `Slopguard: attached author reply to ${record.itemId} (u/${record.authorName}, ${body.length} chars)`,
  );

  // Optional LLM-aided reply classification — only when LLM escalation is
  // enabled AND a Gemini key is configured. The classification is attached
  // to the verify record so mods see it on the review card.
  const settings = await context.settings.getAll();
  if (settings[AppSetting.UseLlmEscalation] !== true) return;
  const geminiKey = (settings[AppSetting.GeminiApiKey] as string) ?? "";
  if (!geminiKey) return;

  // Only classify the FIRST reply. A hostile author can otherwise spam
  // the conversation with long replies and burn the daily spend cap.
  if (record.reply?.classification) {
    console.log(
      `Slopguard: reply already classified for ${record.itemId}, skipping`,
    );
    return;
  }
  // Also skip if the verify-DM was sent >24h ago — stale conversations
  // probably aren't the original verification flow.
  const STALE_REPLY_WINDOW_MS = 1000 * 60 * 60 * 24;
  if (Date.now() - record.sentAt > STALE_REPLY_WINDOW_MS) {
    console.log(
      `Slopguard: verify-DM too old (${Math.floor((Date.now() - record.sentAt) / 3600000)}h), not classifying`,
    );
    return;
  }

  const maxSpend = (settings[AppSetting.MaxDailySpendUsd] as number) ?? 1;
  const spent = await getDailySpend(context);
  if (spent >= maxSpend) {
    console.log("Slopguard: classifier skipped — daily spend cap reached");
    return;
  }

  const classification = await classifyReply(geminiKey, {
    originalScore: record.score,
    topReasons: record.topReasons ?? [],
    replyText: record.reply?.text ?? body,
  });
  await addToDailySpend(context, classification.costUsd);

  // Re-read in case anything else has touched the record concurrently, then
  // write the classification back.
  const latest = await readVerify(context, record.itemId);
  if (!latest || !latest.reply) return;
  latest.reply.classification = {
    category: classification.category,
    confidence: classification.confidence,
    reasoning: classification.reasoning,
    classifiedAt: Date.now(),
  };
  await writeVerify(context, latest);
  console.log(
    `Slopguard: reply classified as ${classification.category} (${(classification.confidence * 100).toFixed(0)}%) for ${record.itemId}`,
  );
}
