import type { ModMail } from "@devvit/protos";
import type { TriggerContext } from "@devvit/public-api";
import { attachReplyByConversation } from "../lib/verifyAuthor.js";
import { markHandled } from "../redis.js";

/**
 * Catches replies from authors to our verify-author DM and attaches the
 * reply text to the score's review card.
 *
 * Filters:
 *   - Must be from `participant_user` (the author, not a mod or internal)
 *   - Must not be auto-generated (no loops)
 *   - Must match a conversationId we previously sent (verifyAuthor's
 *     reverse index `sg:verify-conv:<convId>`)
 *
 * The trigger fires for *every* modmail event in the sub, so the cheap
 * conversationId lookup in Redis is what gates us to only our own threads.
 */
export async function onModMail(
  event: ModMail,
  context: TriggerContext,
): Promise<void> {
  if (!event.conversationId || !event.messageId) return;
  if (event.isAutoGenerated) return;

  // Only the post/comment author's reply matters — skip mod-side messages
  // and internal mod-discussion messages.
  if (event.messageAuthorType !== "participant_user") return;

  // Dedupe — same messageId can re-fire.
  const dedup = await markHandled(
    context,
    "modMail",
    event.messageId,
  );
  if (!dedup) return;

  // Fetch the conversation to get message bodies.
  let body = "";
  try {
    const res = await context.reddit.modMail.getConversation({
      conversationId: event.conversationId,
      markRead: false,
    });
    const messages = res.conversation?.messages ?? {};
    // Take the message that matches event.messageId; fall back to latest
    // participant_user message if exact match isn't found.
    const exact = messages[event.messageId];
    if (exact) {
      body = exact.bodyMarkdown ?? exact.body ?? "";
    } else {
      const userMessages = Object.values(messages)
        .filter(m => m.participatingAs === "participant_user")
        .sort((a, b) => (a.date ?? "").localeCompare(b.date ?? ""));
      const last = userMessages[userMessages.length - 1];
      body = last?.bodyMarkdown ?? last?.body ?? "";
    }
  } catch (err) {
    console.warn(
      `Slopguard onModMail: failed to fetch conversation ${event.conversationId}: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
    return;
  }

  if (!body.trim()) return;

  const record = await attachReplyByConversation(context, {
    conversationId: event.conversationId,
    replyText: body,
  });

  if (record) {
    console.log(
      `Slopguard: attached author reply to ${record.itemId} (u/${record.authorName}, ${body.length} chars)`,
    );
  }
}
