import type { TriggerContext, ScheduledJobEvent } from "@devvit/public-api";
import { getDailyMetrics, getDailySpend } from "../redis.js";
import { AppSetting } from "../settings.js";

export const DAILY_METRICS_JOB = "slopguard-daily-metrics";

export async function dailyMetricsHandler(
  _event: ScheduledJobEvent<undefined>,
  context: TriggerContext,
): Promise<void> {
  const settings = await context.settings.getAll();
  if (settings[AppSetting.EnableDailyMetricsPost] === false) return;

  const yesterdayDate = new Date(Date.now() - 1000 * 60 * 60 * 24)
    .toISOString()
    .slice(0, 10);

  const metrics = await getDailyMetrics(context, yesterdayDate);
  if (!metrics) {
    console.log(`Slopguard: no metrics for ${yesterdayDate}; skipping daily post.`);
    return;
  }

  const spend = await getDailySpend(context, yesterdayDate);

  const subredditName =
    context.subredditName ?? (await context.reddit.getCurrentSubredditName());

  const body = [
    `**Slopguard daily summary — ${yesterdayDate}**`,
    "",
    `| Metric | Value |`,
    `|---|---|`,
    `| Items scored | ${metrics.itemsScored} |`,
    `| Flagged as AI | ${metrics.flagged} |`,
    `| Auto-removed | ${metrics.autoRemoved} |`,
    `| Manually removed | ${metrics.manualRemoved} |`,
    `| Estimated time saved | ${metrics.estimatedTimeSavedMinutes} min |`,
    `| API spend | $${spend.toFixed(4)} |`,
    "",
    `*Mod-only post. Generated by [Slopguard](https://developers.reddit.com/apps/slopguard).*`,
  ].join("\n");

  try {
    const post = await context.reddit.submitPost({
      subredditName,
      title: `Slopguard daily summary — ${yesterdayDate}`,
      text: body,
    });
    await post.distinguish();
    console.log(`Slopguard: posted daily metrics ${post.id}`);
  } catch (err) {
    console.error(`Slopguard: failed to post daily metrics: ${(err as Error).message}`);
  }
}
