/**
 * Gemini vision module — V2 opt-in feature with two endpoints:
 *
 *   `classifyImageForAi(url)`  → score 0..1 + reasoning. Catches AI image
 *                                 generation (Stable Diffusion, Midjourney,
 *                                 DALL-E, Sora frames, etc).
 *
 *   `extractTextFromImage(url)` → OCR text. Lets the promo/contact signals
 *                                 see scam text embedded in images
 *                                 (Telegram handles, wallet addresses, "DM
 *                                 me" instructions baked into screenshots).
 *
 * Both are gated by `UseLlmVision` setting + a Gemini API key + the daily
 * spend cap. Costs ~$0.0005-$0.001 per image at Gemini 2.5 Flash rates.
 *
 * The image is fetched server-side then base64-inlined. This is more
 * latency than fileUri but is reliable across regions and Reddit's image
 * hosts (i.redd.it, preview.redd.it) without needing Gemini to fetch them.
 */

const ENDPOINT =
  "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent";

const COST_INPUT_PER_TOKEN = 0.3 / 1_000_000;
const COST_OUTPUT_PER_TOKEN = 2.5 / 1_000_000;
const MAX_IMAGE_BYTES = 5 * 1024 * 1024;

const AI_IMAGE_INSTRUCTION = `You evaluate whether an image was generated by an AI model (Stable Diffusion, Midjourney, DALL-E, FLUX, Sora frame, etc) versus produced by a human (photograph, drawing, painting, screenshot of real content).

Return STRICT JSON:
{
  "score": 0.0 to 1.0  (1.0 = certainly AI-generated, 0.0 = certainly real/human-made),
  "reasoning": "one or two sentences",
  "signals": ["short tags like 'six fingers', 'morphed background', 'over-smooth skin', 'symmetric defects', 'real photo metadata', 'pencil texture', 'authentic shadows'"]
}

Score conservatively. Real photographs, professional art, screenshots, and infographics should NOT be flagged. Only flag when generative artifacts are clearly present. Output JSON ONLY.`;

const OCR_INSTRUCTION = `Extract all readable text from the image. Return STRICT JSON:
{
  "text": "the extracted text exactly as it appears in the image, joined with newlines for separate lines/blocks. Empty string if no text is present."
}
Do not paraphrase. Preserve URLs, handles, phone numbers, wallet addresses verbatim. Output JSON ONLY.`;

export interface VisionResult {
  score: number;
  reasoning: string;
  signals: string[];
  latencyMs: number;
  costUsd: number;
  error?: string;
}

export interface OcrResult {
  text: string;
  latencyMs: number;
  costUsd: number;
  error?: string;
}

interface GeminiResponse {
  candidates?: { content?: { parts?: { text?: string }[] } }[];
  usageMetadata?: {
    promptTokenCount?: number;
    candidatesTokenCount?: number;
  };
  error?: { message?: string };
}

function clamp01(n: unknown): number {
  const v = typeof n === "number" ? n : Number(n);
  if (!Number.isFinite(v)) return 0;
  return Math.max(0, Math.min(1, v));
}

function safeParse<T>(raw: string): T | null {
  const trimmed = raw
    .trim()
    .replace(/^```json\s*/i, "")
    .replace(/```\s*$/i, "");
  try {
    return JSON.parse(trimmed) as T;
  } catch {
    const match = trimmed.match(/\{[\s\S]*\}/);
    if (!match) return null;
    try {
      return JSON.parse(match[0]) as T;
    } catch {
      return null;
    }
  }
}

const FETCH_TIMEOUT_MS = 5000;
const BASE64_CHUNK = 0x8000; // 32KB — avoids per-char string concatenation

function toBase64(bytes: Uint8Array): string {
  // Chunked btoa: turning a 5MB image into a 5M-char string via
  // per-char concatenation is pathological in V8 isolates. Build the
  // binary string in 32KB slices instead.
  let binary = "";
  for (let i = 0; i < bytes.length; i += BASE64_CHUNK) {
    const slice = bytes.subarray(i, i + BASE64_CHUNK);
    binary += String.fromCharCode.apply(
      null,
      Array.from(slice) as unknown as number[],
    );
  }
  return btoa(binary);
}

async function fetchImageBase64(
  url: string,
): Promise<{ data: string; mimeType: string } | null> {
  const ctrl = new AbortController();
  const timer = setTimeout(() => ctrl.abort(), FETCH_TIMEOUT_MS);
  try {
    const res = await fetch(url, { signal: ctrl.signal });
    if (!res.ok) return null;
    const ct = res.headers.get("content-type") ?? "image/jpeg";
    if (!ct.startsWith("image/")) return null;
    // Early-reject oversize responses via Content-Length when available —
    // a malicious 50MB image otherwise downloads fully before the post-
    // buffer size check rejects it.
    const declaredLen = Number(res.headers.get("content-length") ?? "0");
    if (declaredLen > MAX_IMAGE_BYTES) return null;
    const buf = await res.arrayBuffer();
    if (buf.byteLength === 0 || buf.byteLength > MAX_IMAGE_BYTES) return null;
    return { data: toBase64(new Uint8Array(buf)), mimeType: ct };
  } catch {
    return null;
  } finally {
    clearTimeout(timer);
  }
}

async function callGemini(
  apiKey: string,
  systemInstruction: string,
  image: { data: string; mimeType: string },
  maxOutputTokens: number,
): Promise<{
  raw: string;
  costUsd: number;
  error?: string;
}> {
  const res = await fetch(`${ENDPOINT}?key=${encodeURIComponent(apiKey)}`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      system_instruction: { parts: [{ text: systemInstruction }] },
      contents: [
        {
          role: "user",
          parts: [
            { inline_data: { mime_type: image.mimeType, data: image.data } },
          ],
        },
      ],
      generationConfig: {
        temperature: 0.1,
        maxOutputTokens,
        responseMimeType: "application/json",
      },
    }),
  });
  if (!res.ok) {
    const body = await res.text();
    return {
      raw: "",
      costUsd: 0,
      error: `http_${res.status}: ${body.slice(0, 200)}`,
    };
  }
  const data = (await res.json()) as GeminiResponse;
  const raw = data.candidates?.[0]?.content?.parts?.[0]?.text ?? "";
  const inTok = data.usageMetadata?.promptTokenCount ?? 0;
  const outTok = data.usageMetadata?.candidatesTokenCount ?? 0;
  const costUsd = inTok * COST_INPUT_PER_TOKEN + outTok * COST_OUTPUT_PER_TOKEN;
  return { raw, costUsd };
}

export async function classifyImageForAi(
  apiKey: string,
  imageUrl: string,
): Promise<VisionResult> {
  const start = Date.now();
  const img = await fetchImageBase64(imageUrl);
  if (!img) {
    return {
      score: 0,
      reasoning: "image fetch failed or unsupported type",
      signals: [],
      latencyMs: Date.now() - start,
      costUsd: 0,
      error: "fetch_failed",
    };
  }

  try {
    const { raw, costUsd, error } = await callGemini(
      apiKey,
      AI_IMAGE_INSTRUCTION,
      img,
      300,
    );
    if (error) {
      return {
        score: 0,
        reasoning: error,
        signals: [],
        latencyMs: Date.now() - start,
        costUsd: 0,
        error,
      };
    }
    const parsed = safeParse<{
      score?: number;
      reasoning?: string;
      signals?: string[];
    }>(raw);
    return {
      score: clamp01(parsed?.score),
      reasoning: parsed?.reasoning ?? "",
      signals: Array.isArray(parsed?.signals) ? parsed!.signals! : [],
      latencyMs: Date.now() - start,
      costUsd,
    };
  } catch (err) {
    return {
      score: 0,
      reasoning: `vision exception: ${(err as Error).message}`,
      signals: [],
      latencyMs: Date.now() - start,
      costUsd: 0,
      error: "exception",
    };
  }
}

export async function extractTextFromImage(
  apiKey: string,
  imageUrl: string,
): Promise<OcrResult> {
  const start = Date.now();
  const img = await fetchImageBase64(imageUrl);
  if (!img) {
    return {
      text: "",
      latencyMs: Date.now() - start,
      costUsd: 0,
      error: "fetch_failed",
    };
  }

  try {
    const { raw, costUsd, error } = await callGemini(
      apiKey,
      OCR_INSTRUCTION,
      img,
      600,
    );
    if (error) {
      return {
        text: "",
        latencyMs: Date.now() - start,
        costUsd: 0,
        error,
      };
    }
    const parsed = safeParse<{ text?: string }>(raw);
    return {
      text: typeof parsed?.text === "string" ? parsed.text.trim() : "",
      latencyMs: Date.now() - start,
      costUsd,
    };
  } catch (err) {
    return {
      text: "",
      latencyMs: Date.now() - start,
      costUsd: 0,
      error: "exception",
    };
  }
}
